# Generated by Django 2.0.2 on 2019-03-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
